"""empty message

Revision ID: c76ceb114b9c
Revises: d481dd99dffd
Create Date: 2023-12-28 11:44:18.346798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76ceb114b9c'
down_revision = 'd481dd99dffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_code_type', ['code', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.drop_constraint('unique_code_type', type_='unique')

    # ### end Alembic commands ###
