"""empty message

Revision ID: d481dd99dffd
Revises: 0cb4a4c0ce1b
Create Date: 2023-12-28 11:40:36.793343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd481dd99dffd'
down_revision = '0cb4a4c0ce1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
